### PR TITLE
Update mail.rb

### PR DESCRIPTION
**Pull request by milep**
fix typo

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @milep,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md#cla">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by thinkingserious** [comment]
Hello @milep,

Good catch, thanks! Please let us know if you do not want to sign the CLA and we will go ahead and make the change ourselves. Otherwise, we will await receipt of the [signed CLA](https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md#cla) from you. Thanks!

**Comment by milep** [comment]
Hi,

You can do the change, it was just easier to point out with pull request.

- Miika

**Comment by thinkingserious** [comment]
@milep,

You are awesome, thanks! We still want to reward your efforts with some swag. Please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) so we can do so.

**Pull request closed without merging**
