### PR TITLE
Remove puts from mail.rb

### PR DESCRIPTION
**Pull request by mikedebock**
Remove two puts method-calls from mail.rb
This affects the output of the unit tests of my project.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Thanks! We appreciate your support!

**Comment by thinkingserious** [comment]
Thanks for contributing to SendGrid Open Source! We think it's awesome when community members contribute to our projects and want to celebrate that.

The following link will ask you to authenticate with Github (so we can verify your identity). You'll then be asked for your shipping address so that we can send you a thanks for contributing.

[Click Here to Continue »](https://sendgrid-contribot.herokuapp.com/)

Once again, thank you!

**Comment by mikedebock** [comment]
You're welcome, nice to hear that you appreciate it!

**Comment by BrandonCsSanders** [comment]
My thanks as well @mikedebock ... any chance we could get a version bump on the gem to 1.0.5 so that we can get the benefit of this from the official gem?

**Comment by thinkingserious** [comment]
@BrandonCsSanders pushed: https://rubygems.org/gems/sendgrid-ruby

Thanks again!

**Comment by BrandonCsSanders** [comment]
@thinkingserious thanks for the quick turnaround :+1:

**Pull request merged**
