### PR TITLE
Add ability to impersonate subuser

### LINKED ISSUE #270: Add the ability to impersonate a subuser
Please see the [Python implementation](https://github.com/sendgrid/sendgrid-python/pull/314) for an example.

### PR DESCRIPTION
**Pull request by danilospa**
Resolves #270 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- It enables a `impersonate_subuser` parameter on client initialize function. When it's filled, the header `On-Behalf-Of` is added.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=271) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=271) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=271) it.</sub>

**Comment by danilospa** [comment]
The following tests are breaking because corresponding files do not exist:
`test_docker_compose_exists`, `test_docker_exists`, `test_codeclimate_exists`.
May I remove these tests on this same PR?

**Comment by jagthedrummer** [comment]
I'd love to see this get merged.

**Comment by thinkingserious** [comment]
Thanks for the vote @jagthedrummer!

This PR is on our backlog to merge and your vote helps give it priority.

**Comment by clee** [comment]
LGTM - this PR is almost identical to #272, but I think the tests in this one are slightly better. I'd vote we merge this one.

**Comment by thinkingserious** [comment]
Hello @danilospa,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by Shadowssong** [comment]
Hi @thinkingserious do you know when the next release plans to happen?  I would like to use this feature but its only on master and has not been released yet (as far as I can tell).

**Pull request merged**
