### PR TITLE
Support for dynamic template data.

### PR DESCRIPTION
**Pull request by nedcampion**
This is an initial take on adding support for newly [added dynamic templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html).

I've added an `add_dynamic_tempalte_data` method to the `Personalization` class as well as a test and some example code to show how it would be used.

Fixes #300

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=300) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=300) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=300) it.</sub>

**Comment by thinkingserious** [comment]
This is awesome @nedcampion!

Are you having an issue with our CLA? Is should be pretty quick and simple to get that signed, just need to [click here](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=300) and fill out a short form.

Thanks!

With Best Regards,

Elmer

**Comment by nedcampion** [comment]
I think I got it signed properly, but let me know if I missed something @thinkingserious. Also, I think this is going to fail the the test suite (as the last PR did) because of three other tests that are failing.

**Comment by thinkingserious** [comment]
You got it @nedcampion! I'll get the other tests squared away :)

**Comment by lucaswhitman** [comment]
Any chance this one is coming in soon? I'm very excited... 😁

**Comment by thinkingserious** [comment]
Hello @lucaswhitman,

I'm currently in the process of adding dynamic template support for all of our libraries, including Ruby. My apologies for the delay and unfortunately I don't have a solid ETA just yet.

With Best Regards,

Elmer

**Comment by lucaswhitman** [comment]
@thinkingserious no worries, I'm pulling together a work around for now, just thought I'd check before committing to it. Thanks for the update!

**Comment by metaskills** [comment]
> I'm currently in the process of adding dynamic template support for all of our libraries, including Ruby. 

FWIW, I am doing this now with the current client with the method `client.mail._('send').post(request_body: data)` where data is as described in this article (https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html) but with one error.

In the article, the `template_id` should be at the root of the JSON object, not under `personalizations`.

**Comment by lucaswhitman** [comment]
@metaskills - thanks for the follow up! I'm walking down that road this morning and just sent my first successful test email.

**Comment by thinkingserious** [comment]
Hello @nedcampion,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @nedcampion,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by haffla** [comment]
What's stopping this from being released?

Last release Oct 2017!

**Comment by thinkingserious** [comment]
Hello @haffla,

We now just have Java and Go coming up next before this one. It should not be much longer.

With Best Regards,

Elmer

**Comment by khuongnguyenBlue** [comment]
@nedcampion @thinkingserious 
it seems doesn't work anymore. 
NoMethodError: undefined method `add_dynamic_template_data' for #<SendGrid::Personalization:0x000000000713cc78>
Pls tell me what to do, thank you!

**Comment by Davidslv** [comment]
Can we have this released, please?

**Comment by thinkingserious** [comment]
Hi @Davidslv,

Yes, this will be released soon. I'm close to releasing Java, then we will release Go and then I'll get this one out there.

My apologies for the delay and thank you for your patience.

With Best Regards,

Elmer

**Pull request merged**
