### PR TITLE
Remove broken link

### PR DESCRIPTION
**Pull request by KrauseFx**
Not sure where this should point to, feel free to just close this PR and add the right path instead :+1:

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=283) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=283) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=283) it.</sub>

**Comment by thinkingserious** [comment]
Hi @KrauseFx,

Thanks for taking the time to make a PR! If you still want us to merge it, here is the correct link: https://github.com/sendgrid/sendgrid-ruby/tree/master/lib/sendgrid/helpers/inbound/sample_data

We would also need you to [sign our CLA](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=283), which should not take more than a few minutes. It's a simple web form.

With Best Regards,

Elmer

**Comment by KrauseFx** [comment]
Thanks, that's fine, feel free to take the change and apply it again 👍

**Comment by thinkingserious** [comment]
Awesome, I've made the update. Thanks!

**Comment by KrauseFx** [comment]
Thanks 👍

**Pull request closed without merging**
