### PR TITLE
Fix unexpected `Mail` `#categories`, `#categories=` behavior

### PR DESCRIPTION
**Pull request by tkbky**
This change makes `Mail#categories=` to only accept `Category` as its argument, otherwise, we would need to consider more cases if we allow it to accept different types of argument, and if not handle well, its behavior will be inconsistent.

I'm not sure if we should accept an array of `Category` as well, or probably we should just accept an array instead.

p/s: I've signed the CLA

### CODE REVIEW

**Comment by swifthand** [comment]
I agree that use of `#to_json` only to immediate fetch just one key feels like redundant work when you could instead ask the `Category` object directly via `#category`. However that does seem to be the way the whole library is tied together: Everything has a `#to_json` method, and many methods accepts any object which has a `#to_json` method, so long as it produces the appropriate Hash.

Both the original interface (must have `#to_json`) and the interface of this proposed change (must have `#name`) are so small that a strict restriction to a `Category` object feels unnecessary.

Setting aside whether breaking the consistency of using `#to_json` everywhere, if all you need is a `:name` method, isn't it preferable to raise `unless respond_to?(:name)`?

A related issue is https://github.com/sendgrid/sendgrid-ruby/issues/95 which references all of the array assignment methods, converting the use of `categories=` from being a wrapper for `push` into the more explicit `add_category`.

**Comment by thinkingserious** [comment]
@tkbky,

Thank you for the pull request!

Thanks for the detailed feedback @swifthand. 

I think #95 is the way to go for this particular issue.

On the bigger issue of the `to_json` design decision (among others), now is the chance to weigh in on a refactor. If you have a moment, please check out the [Mail Helper Enhancement ](https://github.com/sendgrid/sendgrid-ruby/projects) project.

**Comment by tkbky** [comment]
Agree with @swifthand on the unnecessary restriction.

@thinkingserious Yep, I think #95 (didn't notice that earlier) is the way to go. How should we proceed from here?

**Comment by thinkingserious** [comment]
@tkbky,

If you still want to tackle the issue, I suggest you just update this PR. Unless it's easier to just create a new one. Either is fine with me. 

Thanks!

**Comment by thinkingserious** [comment]
I'm going to fork your pull request to make some further changes. Since this will be a breaking a changes there are few other things I'd like do while we have the hood up. Once I'm done, I'll make a pull request against your fork.

Here is what I will be doing:

1. Split the classes into their own files
2. Make sure we handle all cases of arrays consistently ([example](https://github.com/tkbky/sendgrid-ruby/blob/e59d1d20de8d306855e8c0f43b0d12712b682532/lib/sendgrid/helpers/mail/mail.rb#L723))

Thanks!

**Comment by tkbky** [comment]
@thinkingserious Great! I always hope the classes inside `mail.rb` could be live in their own files. And yes, the hashes must be handled consistently too (which I was planning in another PR but never mind now 😄 ). Looking forward to your changes. 😃

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=108) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=108) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: thinkingserious<br/>:x: tkbky<br/><hr/>**tkbky** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=108) it.</sub>

**Comment by thinkingserious** [comment]
@tkbky,

Could you please take a moment to sign our new CLA? Now you just need to [click this link](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=108) and fill out a short form. There is no downloading and signing anymore :)

**Comment by tkbky** [comment]
@thinkingserious Done!

**Comment by thinkingserious** [comment]
Hello @tkbky,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Thanks again to @mootpointer and @swifthand for your help on this one!

**Pull request merged**
