### PR TITLE
fix typo in initialize methods

### PR DESCRIPTION
**Pull request by benjackson84**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @benjackson84,

Thanks for the PR!

To merge it, I need a [signed CLA](https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md#cla), could you please do that for us?

With Best Regards,

Elmer

**Comment by benjackson84** [comment]
@thinkingserious CLA signed an emailed over last week.

**Comment by mbernier** [comment]
Hey @benjackson84, sorry about the duplicate email. We recently added and automator to our github repo (see that reply speed!?!!). This thing is new and doesn't have the same list of people who have signed the CLA, so it's asking everyone for the CLA again. 

My apologies on this count, the next step is going to be to make it have a small database to solve this problem :) 

Thanks!!

**Comment by thinkingserious** [comment]
@benjackson84,

This is on our backlog to merge. Thanks again for your support!

**Comment by thinkingserious** [comment]
Hello @benjackson84,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
