### PR TITLE
FIX-274: Fix travis warning

### LINKED ISSUE #274: Variable issues in testing
#### Issue Summary

I found this in the Travis log - 

```
/home/travis/build/sendgrid/sendgrid-ruby/lib/sendgrid/helpers/mail/category.rb:11: warning: method redefined; discarding old name=
/home/travis/build/sendgrid/sendgrid-ruby/lib/sendgrid/helpers/mail/category.rb:15: warning: method redefined; discarding old name
/home/travis/build/sendgrid/sendgrid-ruby/lib/sendgrid/helpers/stats/stats_response.rb:25: warning: assigned but unused variable - metrics
```

### PR DESCRIPTION
**Pull request by rahul26goyal**
# Fixes #274 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Remove duplicate declaration on name variable from category.rb
- Remove unused variable from stat_response.rb.

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by rahul26goyal** [comment]
@thinkingserious  how can u debug why the travis integration is breaking?

**Comment by thinkingserious** [comment]
Hi @rahul26goyal ,

Generally, a combination of examining the [local test results](https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md#testing) vs the [Travis CI logs](https://travis-ci.org/sendgrid/sendgrid-ruby/builds/296356018?utm_source=github_status&utm_medium=notification) does the trick.

**Comment by rahul26goyal** [comment]
hi @thinkingserious 
Three unit tests on travis are failing.

**Comment by thinkingserious** [comment]
Hi @rahul26goyal,

Yes, those tests are expected to fail for now, they will not effect the merging of your PR. We are currently behind schedule in closing PRs right now due to an amazing flood of over 1,000 PRs last month for Hacktoberfest.

We appreciate your patience as we work through the backlog.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @rahul26goyal,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
