### PR TITLE
Fix personalization example

### PR DESCRIPTION
**Pull request by thiagogsr**
After upgrade to 5.0.0 the method `personalizations=` no longer exists.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=165) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=165) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=165) it.</sub>

**Comment by thinkingserious** [comment]
Good catch, thanks!

**Comment by thinkingserious** [comment]
Hello @thiagogsr,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thiagogsr** [comment]
Hi @thinkingserious, thank you all for the gifts, I really appreciate it.

**Comment by thinkingserious** [comment]
It is our pleasure, thanks for your support!

**Pull request merged**
