### PR TITLE
Updated sinatra version to 2.0

### PR DESCRIPTION
**Pull request by gkats**
Fixes bundler dependency issues with rails >5.0 and rack 2.0.

Solves: #159

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=160) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=160) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=160) it.</sub>

**Comment by gkats** [comment]
To whoever reviews this, please note that I had some trouble running the tests locally. 

Setup:
- Debian 8.0
- prism v2.0.0-alpha.3

I had to change `prism run --spec <path-to-config>` to `prism serve -c <path-to-config>`. Maybe we should change `prism.sh` to download a specific version of prism?

**Comment by gkats** [comment]
Last thing, if it helps, I added a local build of the gem in an existing Ruby v2.3 and Rails v5.0 project with a bunch of other gems. Bundler installs like a charm.

**Comment by thinkingserious** [comment]
@pytlesk4 thoughts on @gkats prism comment above? Thanks!

**Comment by thinkingserious** [comment]
Hello @gkats,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by pytlesk4** [comment]
@elmer, you guys should hard code the version of prism, or always download the latest 0.x.x release. 2.x.x is a completely different version of prism and it will break all your tests. I would check all your sdks to make sure they aren't downloading latest version of prism.

**Pull request merged**
