### PR TITLE
Add attr_accessor for cc_name and bcc_name

### PR DESCRIPTION
**Pull request by DylanGriffith**
Looks like this was missing. Let me know if this was intentional and I'll close the PR.

### CODE REVIEW

**Comment by qnm** [comment]
@eddiezane Anything we can do to assist with getting this merged?

**Comment by eddiezane** [comment]
@qnm apologies but I no longer work at SendGrid.

@thinkingserious or @mbernier should be able to help out.

**Comment by qnm** [comment]
@eddiezane Thanks for letting me know. Apologies for pulling you into this thread!

**Comment by thinkingserious** [comment]
Thanks for the pull request @DylanGriffith and the follow up @qnm. We have this one on our backlog and we'll check it out ASAP.

**Comment by thinkingserious** [comment]
Thanks for contributing to SendGrid Open Source! We think it's awesome when community members contribute to our projects and want to celebrate that.

The following link will ask you to authenticate with Github (so we can verify your identity). You'll then be asked for your shipping address so that we can send you a thanks for contributing.

[Click Here to Continue »](https://sendgrid-contribot.herokuapp.com/)

Once again, thank you!

**Pull request merged**
