### PR TITLE
Add a unittest to check the license.md file date range #250

### LINKED ISSUE #250: Add a unittest to check the license.md file date range
The end year in the license file should be "this year" and this should be checked on every run of the tests. If the end year is no correct, fail the test.
example: 
> Copyright (c) 2012-2016 SendGrid, Inc.
It is 2017, so this should be:
> Copyright (c) 2012-2017 SendGrid, Inc.
and the  test should fail.
--done

### PR DESCRIPTION
**Pull request by prashuchaudhary**
Fixes #250 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Added unittest to check for specific repo files mentioned in #251 

If you have questions, please send an email to Sendgrid, or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=255) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=255) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=255) it.</sub>

**Comment by prashuchaudhary** [comment]
@mbernier PR: #255

**Comment by prashuchaudhary** [comment]
@mbernier Right now the build is failing because LICENSE.txt year range is not updated. It is *2014-2016* as opposed to current year range *2014-2017*

**Comment by mbernier** [comment]
@prashuchaudhary I merged the conflicts, will come back and check on this in a bit.

**Comment by mbernier** [comment]
I am not seeing this test run - I know that the file checks are there and failing (this is expected and OK), is that preventing this test from running? Here's what I see: 
```
Finished in 256.773284s, 1.0788 runs/s, 1.1177 assertions/s.
  1) Failure:
TestAPI#test_docker_compose_exists [/home/travis/build/sendgrid/sendgrid-ruby/test/sendgrid/test_sendgrid-ruby.rb:2685]:
Expected false to be truthy.
  2) Failure:
TestAPI#test_codeclimate_exists [/home/travis/build/sendgrid/sendgrid-ruby/test/sendgrid/test_sendgrid-ruby.rb:2701]:
Expected false to be truthy.
  3) Failure:
TestAPI#test_docker_exists [/home/travis/build/sendgrid/sendgrid-ruby/test/sendgrid/test_sendgrid-ruby.rb:2681]:
Expected false to be truthy.
277 runs, 287 assertions, 3 failures, 0 errors, 0 skips
Prism shut down
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/home/travis/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib" "/home/travis/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/rake_test_loader.rb"
```
Your test was added to `test_sendgrid-ruby.rb, but I don't see output saying that this specific test is failing: 

``` "test/sendgrid/test_sendgrid-ruby.rb" "test/sendgrid/helpers/mail/test_category.rb" "test/sendgrid/helpers/mail/test_email.rb" "test/sendgrid/helpers/mail/test_mail.rb" "test/sendgrid/helpers/mail/test_personalizations.rb" ]
/home/travis/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
The command "rake test" exited with 1.
4.29s$ rake spec
/home/travis/.rvm/rubies/ruby-2.4.1/bin/ruby -I/home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-support-3.7.0/lib:/home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.0/lib /home/travis/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
```

**Comment by mbernier** [comment]
and then .... it looks like the [License file on your master branch](https://github.com/prashuchaudhary/sendgrid-ruby/blob/master/LICENSE.txt) is up to date with the 2017 - so it's working exactly as expected! I will go ahead and merge. Thank you!

**Comment by thinkingserious** [comment]
Hello @prashuchaudhary,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
