### PR TITLE
Switch expectation and actual assertion

### PR DESCRIPTION
**Pull request by billywatson**
The expected value and actual value were reversed

### CODE REVIEW

**Comment by billywatson** [comment]
I've definitely followed those directions now and on this particular branch (switch-expectation-and-actual-assertion) all the tests are passing with ruby 2.2. The other branch is the one trying to remove the ruby 2.2 requirement and I'll try again there. 

That being said, since I was able to get all the tests to pass on this branch, why is Travis CI failing?

**Comment by billywatson** [comment]
Never mind, I see comments on PR #70 so I'll just wait for that, but as far as I can tell this particular branch can be merged.

**Comment by thinkingserious** [comment]
It looks like you fixed this one in your other pull request: https://github.com/sendgrid/sendgrid-ruby/pull/72

So I'll close this one and merge the other one. Please let me know if I am mistaken. Thanks!

**Comment by billywatson** [comment]
I ended up separating the two into separate pulls. Not sure if that was necessary. Some people like it separate, others don't.

**Comment by billywatson** [comment]
Well, actually, I might've messed that up so if it's indeed in the other pull request, I don't care. Merge it all together. :)

**Comment by thinkingserious** [comment]
@billywatson,

To make sure I'm clear, should I just merge this pull? Thanks!

Also, please email us at dx@sendgrid.com with your T-shirt size and mailing address so we can send you some swag.

**Comment by billywatson** [comment]
no, don't merge this one. I was mistaken on how to accomplish the pull request split. I know now, but it's not worth it. Merging https://github.com/sendgrid/sendgrid-ruby/pull/72 after merging the http client pull https://github.com/sendgrid/ruby-http-client/pull/2 will be sufficient.

**Pull request closed without merging**
