### PR TITLE
make inclusion of sinatra optional

### PR DESCRIPTION
**Pull request by jjb**
from discussion in #175

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=284) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=284) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=284) it.</sub>

**Comment by jjb** [comment]
the CI failures seem to be unrelated to my work... i could test this by submitting a PR off of master with a dummy commit, but don't want to confuse things / waste resources. let me know if you think my PR is the cause of the failures and i'll look into it.

**Comment by clee** [comment]
No, those failures don’t appear to be related to your code. Don’t worry about making any changes yet; you might need to rebase after some other PRs get merged though.

**Comment by joevandyk** [comment]
what's needed to be done on this?

**Comment by thinkingserious** [comment]
Hello @joevandyk,

The ball is in our court to merge this. It's on our backlog to merge and your vote has been added to help boost the priority.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @jjb,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
