### PR TITLE
Allow users to provide rfc822 formatted email

### LINKED ISSUE #223: Allows users to submit rfc822 formatted email addresses
#### Issue Summary

Similar to: https://github.com/sendgrid/sendgrid-python/pull/348

Where the user can submit email addresses as:
`example@example.com`
or 
`example example <example@example.com>`

### PR DESCRIPTION
**Pull request by czlowieq**
Fixes #223

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=239) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=239) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=239) it.</sub>

**Comment by mbernier** [comment]
@czlowieq I am checking in to see if you can please sign the CLA so we can review your contribution?

**Comment by czlowieq** [comment]
@mbernier I did sign the CLA. I checked it just now and it even says I signed it. Unless I should get some email confirmation, then I haven't got one.

**Comment by mbernier** [comment]
Super strange, it is working - maybe it just needed to recheck? Doesn't matter now, we're good to go!

**Comment by thinkingserious** [comment]
Hello @czlowieq,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
@czlowieq 
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Pull request merged**
