### PR TITLE
feat: Auto Generate Plain Text Content from HTML

### LINKED ISSUE #180: Auto Generate Plain Text Content from HTML
We require both HTML and Plain Text content for improved deliverability. In some cases, only HTML may be available. We need a function that automatically converts a given HTML string to the Plain Text equivalent.

### PR DESCRIPTION
**Pull request by Youssefares**
Added private method to mail class to generate add to generate plain text (if not present) to self.contents, given content with type html using Nokogiri.
I added a simple test as well; feel free to request more. 

Also please point me towards the best place to call the generation method. Do we call it on send when only one content object is present in the contents array? Please clarify..

This should resolve #180

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=188) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=188) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=188) it.</sub>

**Comment by Youssefares** [comment]
@thinkingserious hello there, would appreciate some input :smile: .

**Comment by Youssefares** [comment]
Hey, is this ready for merge? Let me know please so we can merge this in october :smile:

**Comment by thinkingserious** [comment]
Hi @Youssefares,

You have definitely earned your [hacktoberfest](https://sendgrid.com/blog/announcing-hacktoberfest-2017/) prize, no worries :)

I want to avoid new dependencies whenever possible, would you mind presenting your solution in our USE_CASES.md section instead?

With Best Regards,

Elmer

**Comment by mbernier** [comment]
@Youssefares

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by thinkingserious** [comment]
Hi @Youssefares,

Have you been able to consider my suggestion about moving this work over to USE_CASES.md?

Thanks!

With Best Regards,

Elmer

**Comment by Youssefares** [comment]
Hey @thinkingserious , 
Sorry have been a bit busy lately. So to make sure I understand, in use_cases.md we'd add a few lines that advises for more accurate results, supplying both plain-text and html using the Nokogiri gem?
And a short example snippet? Something like that?

**Comment by thinkingserious** [comment]
Hi @Youssefares,

Yes, I think you got it!

**Comment by thinkingserious** [comment]
Closing until PR feedback is addressed.

**Pull request closed without merging**
