### PR TITLE
Fixes version ambiguity in gemspec

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by thinkingserious** [comment]
@cmckni3,

I think I know why the tests are failing for you, I need to [update this code](https://github.com/sendgrid/sendgrid-ruby/blob/master/test/sendgrid/test_sendgrid-ruby.rb#L29) to no longer pull the environment variable as that variable does not get pulled for those outside of the sendgrid organization. I'll fix that and get this merged.

In the mean time, could you please [sign our CLA](https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md#cla) so that I can merge your changes? Thanks!

**Comment by cmckni3** [comment]
Good deal. I was wondering why it was fine locally but not on Travis.

Sure, I can sign the CLA.

**Comment by thinkingserious** [comment]
@cmckni3,

Could you please update your branch to the latest release? https://github.com/sendgrid/sendgrid-ruby/releases/tag/v4.0.6

Thanks!

**Comment by cmckni3** [comment]
@thinkingserious Done. Waiting for Travis

**Comment by cmckni3** [comment]
@thinkingserious thoughts?

**Comment by thinkingserious** [comment]
@cmckni3,

This one is in our queue to review and merge.

Apologies for the delay, Hacktoberfest went really well and we have a unusual amount of issues and pull requests to get done currently.

**Comment by cmckni3** [comment]
No problem. Was just making sure it wasn't forgotten.

**Comment by cmckni3** [comment]
Rebased my branch

**Comment by thinkingserious** [comment]
Hi @cmckni3,

Looks we need one more rebase to get this one out the door. Thanks!

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=112) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=112) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=112) it.</sub>

**Comment by cmckni3** [comment]
Rebased

**Comment by cmckni3** [comment]
Do I need to sign the CLA again?

**Comment by thinkingserious** [comment]
Hello @cmckni3,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by cmckni3** [comment]
@thinkingserious Glad to help out!

I filled out the form 😃

**Comment by thinkingserious** [comment]
Awesome, thank you! We hope you enjoy the swag :)

**Comment by cmckni3** [comment]
Forgot to mention, the swag is awesome. Thanks again!

**Comment by thinkingserious** [comment]
Thanks for the follow up!

If you get a PR accepted this month, there is some [new exclusive swag](https://sendgrid.com/blog/announcing-hacktoberfest-2017/) for you ;)

With Best Regards,

Elmer

**Comment by cmckni3** [comment]
Awesome! Thanks for the heads up!

**Pull request merged**
