### PR TITLE
set api_key to empty string

### PR DESCRIPTION
**Pull request by Gwash3189**
Please see #146 for description of changes.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @Gwash3189,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md#cla">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by Gwash3189** [comment]
@thinkingserious as previously mentioned, new PR following contributing guidelines.

**Comment by Gwash3189** [comment]
@thinkingserious any word on getting this merged?

**Comment by thinkingserious** [comment]
Hi @Gwash3189,

Thanks for checking in. Currently this issue is still making its way up our backlog queue. Any votes or comments on this issues from others will help bump its priority.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @Gwash3189,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
