### PR TITLE
remove unnecessary ruby 2.2 requirement

### PR DESCRIPTION
**Pull request by billywatson**
I was unable to run all the tests b/c of this issue https://github.com/sendgrid/sendgrid-ruby/issues/71, but the two tests that did run passed. I'm letting travis take over.

See my comments on the PR on ruby-http-client for more info https://github.com/sendgrid/ruby-http-client/pull/2

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hi @billywatson,

First of all, thanks for the pull request!

To merge it, we'll need a signed CLA: https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md#cla

Apologies on the tests issue. The tl;dr; is that if you download prism: https://stoplight.io/prism/ and run the command: `./prism run --mock --list --spec https://api.stoplight.io/v1/versions/563a5309daad691100fb05af/export/stoplight.json` a mock SendGrid server will spin up locally under port 4010 and the tests will run.

We are working on making this process automated (we already did so for Go https://github.com/sendgrid/sendgrid-go/blob/master/CHANGELOG.md#302---2016-07-07, both for local testing and within Travis so that the environment variable is no longer needed to access the hosted mock server). Please stay tuned for the update here in this library.

**Comment by billywatson** [comment]
I'm working on the agreement. 

My only issue with the prism stuff is that it should get documented ASAP in the contribution docs until it's changed to be automated. I'll be happy to submit another PR with changes to the README and such, if you'd like.

**Comment by thinkingserious** [comment]
We have received the CLA, thanks!

If you want to add the Prism documentation in, that would be great! Otherwise, I'll open a ticket and get that prioritized.

**Comment by billywatson** [comment]
I'll add the documentation in after I get the test environment set up. That way I've documented something that for sure works (at least for me), then we can go from there.

**Comment by billywatson** [comment]
In other words, it might take me a couple hours to get it all going tomorrow morning (hopefully not).

**Comment by billywatson** [comment]
Hi, I ran the server and it looks like a lot of the tests now pass. However, a lot of tests are still failing. But even when I run them on ruby 2.2, they continue to fail. 

I noticed one of the failures was that an endpoint didn't exist and when I checked the stoplight.json, that endpoint definitely wasn't in there.

Is that the newest stoplight.json file?

**Comment by thinkingserious** [comment]
@billywatson,

Yes, that link pulls the latest stoplight.json.

I just tested and no tests should be failing. Could you please tell me which tests are failing? Thanks!

**Comment by billywatson** [comment]
okay after following the directions on the other PR, I'm now down to one failing test, which I should hopefully be able to figure out for ruby 2.1. The existing code works on 2.2, but I'll test whatever changes I make on both ruby versions to make sure I didn't break anything.


```bash
  1) Error:
TestAPI#test_contactdb_recipients_search_get:
URI::InvalidURIError: bad URI(is not URI?): http://localhost:4010/v3/contactdb/recipients/search?%7Bfield_name%7D=test_string&{field_name}=test_string
    /Users/williamrwatson/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/uri/common.rb:176:in `split'
    /Users/williamrwatson/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
    /Users/williamrwatson/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
    /Users/williamrwatson/.rvm/gems/ruby-2.1.8@sendgrid-ruby/bundler/gems/ruby-http-client-5a06da6e6d0a/lib/ruby_http_client.rb:131:in `build_url'
    /Users/williamrwatson/.rvm/gems/ruby-2.1.8@sendgrid-ruby/bundler/gems/ruby-http-client-5a06da6e6d0a/lib/ruby_http_client.rb:144:in `build_request'
    /Users/williamrwatson/.rvm/gems/ruby-2.1.8@sendgrid-ruby/bundler/gems/ruby-http-client-5a06da6e6d0a/lib/ruby_http_client.rb:221:in `method_missing'
    /Users/williamrwatson/development/sendgrid-ruby/test/sendgrid/test_sendgrid-ruby.rb:802:in `test_contactdb_recipients_search_get'
```

**Comment by thinkingserious** [comment]
Looks like you fixed it with that last commit.

There was an error in our swagger spec that caused that, I've put in a request for a fix.

**Comment by thinkingserious** [comment]
Note: merge this one first: https://github.com/sendgrid/ruby-http-client/pull/2

**Comment by adamdunson** [comment]
:+1: Looks good to me.

**Comment by thinkingserious** [comment]
Thanks for helping increase the priority @adamdunson!

**Comment by thinkingserious** [comment]
Hello @billywatson,

This one finally made it to the top of my queue. 

Do you mind fixing up the conflicts so I can merge? 

Thanks!

**Comment by billywatson** [comment]
Sure

**Comment by billywatson** [comment]
@thinkingserious I've resolved everything and the tests are passing locally. Hopefully CI passes.

**Comment by billywatson** [comment]
@thinkingserious yeah I think something is still wrong in the CI configuration

**Comment by thinkingserious** [comment]
@billywatson Can you email us with your T-shirt size and mailing address? Thanks!

**Comment by thinkingserious** [comment]
@billywatson,

Yes, it still needs the pull to come from someone belonging to the sendgrid org to work.

No worries though, I tested locally and everything was good. Thanks!

**Comment by thinkingserious** [comment]
@billywatson,

Ah yes, there is some other issue going on with the tests. I think it's a Travis issue.

**Pull request merged**
