### PR TITLE
Append custom headers json to payload

### PR DESCRIPTION
**Pull request by pjurewicz**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @pjurewicz,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md#cla">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by thinkingserious** [comment]
Hello @pjurewicz,

As of today, we have not received your [signed CLA](https://github.com/sendgrid/sendgrid-ruby/blob/master/CONTRIBUTING.md#cla). Are you still interested in merging this pull request?

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @pjurewicz,

Are you still interested in merging this PR? Thanks!

**Comment by thinkingserious** [comment]
Hi @pjurewicz,

Our [CLA process](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=144) is now greatly simplified. All you need to do is fill out a short form and click a button :)

Please let me know if you run into any difficulties.

Also, when you get a moment, could you please resolve the conflicts? Thanks!

**Comment by duane** [comment]
@thinkingserious what's going on with this? Is there an ETA to merge? This is a 7-line change; surely you guys can fix this without getting a third party to sign something.

**Comment by duane** [comment]
@thinkingserious if needed, I can reproduce this and actually sign the thing so we can get this merged; please let me know if this is necessary.

**Comment by duane** [comment]
@thinkingserious apologies for the abrupt tone; did not see it until I re-read.

**Comment by thinkingserious** [comment]
@duane,

If you would like to submit a PR with a signed CLA, that would be most appreciated :)

**Comment by mbernier** [comment]
Hey @pjurewicz I am so sorry that we haven't gotten back to this PR. I can tell you though,  that if you are willing to help us out by handling the conflicts (if that's possible) we will get this merged in.

**Comment by thinkingserious** [comment]
Hi @pjurewicz,

Just checking in to see if there is anything I can do to help move this PR forward.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Closing until PR feedback is addressed.

**Pull request closed without merging**
