### PR TITLE
[Closes #258] Add code coverage reporting to codecov

### LINKED ISSUE #258: Add CodeCov support to .travis.yml
Issue Summary

Add this to our travis.ci configuration so that code coverage tests will run!

https://github.com/codecov/example-ruby/blob/master/.travis.yml

### PR DESCRIPTION
**Pull request by rahulpuroht**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
-  This PR add code coverage reporting and integrates it with codecov
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=261) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=261) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=261) it.</sub>

**Comment by thinkingserious** [comment]
@rahulpuroht

We can’t merge your PR without the CLA being signed. 

[ ] **Sign the CLA before November 3rd**
[ ] Tag @mbernier and @thinkingserious to let us know it is signed 

Then we will comment with a link to get your shirt!

**Comment by prathamsharma92** [comment]
Hello,

@mbernier @thinkingserious
Signed the CLA for this Pull Request.Please send a link to get my  shirt :)

**Comment by rahulpuroht** [comment]
Hello,

@mbernier @thinkingseriousSigned the CLA for this Pull Request.Please send a link to get my shirt :)

**Comment by thinkingserious** [comment]
Thanks @rahulpuroht!

[Here](https://dx.sendgrid.com/swag) is the link, enjoy!

**Comment by clee** [comment]
I had to move the code from `test_helper.rb` to `test_sendgrid-ruby.rb` to get this to work, but it didn't break any tests when I did. @rahulpuroht, can you please resubmit with the code moved over?

**Comment by rahulpuroht** [comment]
@clee Hey can you please look into it and suggest why it still showing this errors in Travis.

**Comment by thinkingserious** [comment]
Hi @rahulpuroht,

Those failures are not related to your work. I will still be able to merge this without those tests passing.

Thank you!

With Best Regards,

Elmer

**Comment by benpatterson** [comment]
@thinkingserious this got the `hacktoberfest` label put on it recently, but it sounded like this was going to be merged soon. Do you guys still need help setting up CodeCov?

**Comment by childish-sambino** [comment]
Duplicates https://github.com/sendgrid/sendgrid-ruby/pull/368

**Pull request closed without merging**
