### PR TITLE
Add name as a option to 'from' and 'to' variables

### PR DESCRIPTION
**Pull request by gurgelrenan**
Is not clear how can I set `name` inside the `Email` object, so this is just to make it clear and easier.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=170) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-ruby?pullRequest=170) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-ruby?pullRequest=170) it.</sub>

**Comment by thinkingserious** [comment]
@gurgelrenan,

Do you mind also doing the same for the to variable? Thanks!

**Comment by gurgelrenan** [comment]
@thinkingserious Done!

**Comment by thinkingserious** [comment]
My apologies @gurgelrenan,

I just realized the reason we keep those examples off that particular example is that it is the bare minimum to send an email with SendGrid. [This section](https://github.com/sendgrid/sendgrid-ruby/blob/master/USE_CASES.md) is fore the more complete examples. However, it is currently incomplete.

All that said, we are in the process of major usability update where we would appreciate your feedback. [Do you mind taking a look?](https://github.com/sendgrid/sendgrid-ruby/issues/169) Thanks!

With Best Regards,

Elmer

**Pull request closed without merging**
